namespace Solitaire.Scripts
{
	public enum CardEnums
	{
		ClubAce = 0,
		ClubTwo = 1,
		ClubThree = 2,
		ClubFour = 3,
		ClubFive = 4,
		ClubSix = 5,
		ClubSeven = 6,
		ClubEight = 7,
		ClubNine = 8,
		ClubTen = 9,
		ClubJack = 10,
		ClubQueen = 11,
		ClubKing = 12,
		DiamondAce = 13,
		DiamondTwo = 14,
		DiamondThree = 15,
		DiamondFour = 16,
		DiamondFive = 17,
		DiamondSix = 18,
		DiamondSeven = 19,
		DiamondEight = 20,
		DiamondNine = 21,
		DiamondTen = 22,
		DiamondJack = 23,
		DiamondQueen = 24,
		DiamondKing = 25,
		HeartAce = 26,
		HeartTwo = 27,
		HeartThree = 28,
		HeartFour = 29,
		HeartFive = 30,
		HeartSix = 31,
		HeartSeven = 32,
		HeartEight = 33,
		HeartNine = 34,
		HeartTen = 35,
		HeartJack = 36,
		HeartQueen = 37,
		HeartKing = 38,
		SpadeAce = 39,
		SpadeTwo = 40,
		SpadeThree = 41,
		SpadeFour = 42,
		SpadeFive = 43,
		SpadeSix = 44,
		SpadeSeven = 45,
		SpadeEight = 46,
		SpadeNine = 47,
		SpadeTen = 48,
		SpadeJack = 49,
		SpadeQueen = 50,
		SpadeKing = 51
	}
}
